name: Build and deploy site to GitHub Pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Standard usage
      - uses:  helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: Bundle Jekyll
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build

      # Algolia search index
      - name: Update Algolia index
        if: github.ref == 'refs/heads/master'
        run: |
          bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_KEY }}
